export const SendEmailStyles = {
  modal: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    backdropFilter: "none",
    border: "none",
    borderTopLeftRadius: "16px",
    borderTopRightRadius: "16px",
  },
  box: {
    position: "absolute",
    right: 16,
    width: 400,
    bgcolor: "background.paper",
    borderRadius: 1,
    borderTopLeftRadius: "16px",
    borderTopRightRadius: "16px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: "0.5rem",
    background: "#f2f6fc",
    padding: "0.75rem 0.5rem",
    borderTopLeftRadius: "16px",
    borderTopRightRadius: "16px",
  },
  headerTitle: {
    fontSize: "0.9rem",
    fontWeight: 600,
    color: "#2a2a2a",
  },
  closeButton: {
    width: "22px",
    height: "22px",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    rowGap: "0.5rem",
    padding: "0.2rem 0.5rem",
  },
  inputLabel: {
    display: "flex",
    alignItems: "flex-end",
    borderBottom: "1px solid #ddd",
    paddingBottom: "0.5rem",
  },
  input: {
    flex: 1,
    border: "none",
    outline: "none",
  },
  ccBccToggle: {
    paddingRight: "0.25rem",
    cursor: "pointer",
  },
  textAreaLabel: {
    display: "flex",
    alignItems: "flex-end",
    paddingBottom: "0.5rem",
  },
  textArea: {
    flex: 1,
    border: "none",
    outline: "none",
    resize: "none",
    color: "#2a2a2a",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    padding: "1rem",
  },
};
